# -*- coding: utf-8 -*-
"""handling missing values

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0c_im47h3JEX8lMdxfL0p84GTBH2oj1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/titanic_toy.csv')
df.head()

df.isnull().mean()

df['Age_364'] = df['Age'].fillna(364)
df['Fare_154'] = df['Fare'].fillna(154)
df.head()

print('Orignal age variance is ==',(df['Age'].var()))
print('New age variance is ==',(df['Age_364'].var()))

print('Orignal fare variance is ==',(df['Fare'].var()))
print('New fare variance is ==',(df['Fare_154'].var()))

df.isnull().mean()

fig = plt.figure()
ax = fig.add_subplot(111)
df['Age'].plot(kind='kde',ax=ax,color='red')
df['Age_364'].plot(kind='kde',ax=ax,color='green')
plt.show()

fig = plt.figure()
ax = fig.add_subplot(111)
df['Fare'].plot(kind='kde',ax=ax,color='red')
df['Fare_154'].plot(kind='kde',ax=ax,color='green')
plt.show()

df.cov()

df.corr()

"""**bold text** using SKLEARN
**bold text**
"""

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

imputer1 = SimpleImputer(strategy='constant',fill_value=364)
imputer2 = SimpleImputer(strategy='constant',fill_value=154)

# The transformers argument should be a list of tuples: (name, transformer, columns)
trf = ColumnTransformer([('imputer1', imputer1, ['Age']),
                          ('imputer2', imputer2, ['Fare'])],
                         remainder='passthrough')

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

imputer1 = SimpleImputer(strategy='constant',fill_value=364)
imputer2 = SimpleImputer(strategy='constant',fill_value=154)
trf = ColumnTransformer([('imputer1',imputer1,['Age']),
                         ('imputer2',imputer2,['Fare'])],
                         remainder='passthrough')

trf.fit(df)

under root P ka sq - Q ka sq