# -*- coding: utf-8 -*-
"""LR_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHxLUq8BtRwsx1HBDgze2APLIPlquS3Z
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Salary_Data.csv')

df.head()

df.shape

df.isnull().sum()

plt.scatter(df['YearsExperience'],df['Salary'])
plt.xlabel('YearsExperience')
plt.ylabel('Salary')
plt.show()

sns.pairoiplot(df)

from sklearn.model_selection import train_test_split

x = df.iloc[:,0:1]
y = df.iloc[ :,-1]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state= 20)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train,y_train)

plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,lr.predict(x_train),color='blue')
plt.xlabel('YearsExperience')
plt.ylabel('Salary')
plt.show()

from sklearn.metrics import mean_squared_error,r2_score, mean_absolute_error

y_predict = lr.predict(x_test)

y_test.values

print("MAE",mean_absolute_error(y_test,y_predict))

print("MSE",mean_squared_error(y_test,y_predict))

print("RMSE",np.sqrt(mean_squared_error(y_test,y_predict)))

print("R2_score",r2_score(y_test,y_predict))