# -*- coding: utf-8 -*-
"""web scrapping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQzIqiztyKo9_XKwDB38OHJwLcmeRaMe
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
# giving url
url = "https://www.zameen.com/Houses_Property/Lahore_Johar_Town-93-1.html"
headers = {
    "User-Agent":"Mozilla/5.0"
}
response = requests.get(url,headers=headers)
soup = BeautifulSoup(response.text, "html.parser")
houses = soup.find_all('li',class_='a37d52f0')
len(houses)

prices = soup.find_all('div',class_='_2923a568')
for price in prices:
    print(price.get_text())
len(prices)

areas = soup.find_all('div',class_='cb0c0c514')
for area in areas:
  print(area.get_text)

from bs4 import BeautifulSoup
import bs4
locations = []
for house_listing in houses:
  # Find the div containing the location within each house listing
 if isinstance(house_listing, bs4.element.Tag):
  location_div = house_listing.select_one('div._52d0f124 > .db1aca2f')
  if location_div:
    locations.append(location_div.text.strip())
  else:
     print(f"Skipping element: Expected BeautifulSoup Tag, got {type(house_listing)}")
print(locations)

titles = soup.find_all('h2')
for title in titles:
    print(title.get_text())

bedroom_count=[]
parent_spans = soup.find_all('span',class_='_5ca8f903')
for parent_span in parent_spans:
  if parent_span.find('svg')and parent_span.find('span',class_='_6d9b9b83'):
   bedroom_span = parent_span.find('span',class_='_6d9b9b83')
   bedroom_text = bedroom_span.text.strip()
   if bedroom_text.isdigit():
    bedroom_count.append(int(bedroom_text))
print(bedroom_count)
len(bedroom_count)

prices = []
areas = []
bedroom_count = []
titles = []
for house in houses:
    price = house.find('div',class_='_2923a568').text.strip()
    prices.append(price)
    area = house.find('div',class_='cb0c0c514').text.strip()
    areas.append(area)
    bedroom = house.find('span',class_='_6d9b9b83').text.strip()
    bedroom_count.append(bedroom)
    title = house.find('h2').text.strip()
    titles.append(title)

data = {
    'prices' :prices,
    'areas' :areas,
    'bedroom_count' :bedroom_count,
    'titles' : titles
}
df = pd.DataFrame(data)
df

import requests
from bs4 import BeautifulSoup
import pandas as pd
import random
import time

# User-Agents list
user_agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/112.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/103.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Version/15.1 Safari/605.1.15"
]

houses = []

# Loop through pages 1 to 25
for page in range(1, 26):
    print(f"Scraping page {page}...")
    url = f"https://www.zameen.com/Houses_Property/Lahore_Johar_Town-93-{page}.html"
    headers = {
        "User-Agent": random.choice(user_agents)
    }

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    listings = soup.find_all("li", class_="a37d52f0")

    for listing in listings:
        price = listing.find('div',class_='_2923a568')
        area = listing.find('div',class_='cb0c0514')
        bedroom = listing.find('span',class_='_6d9b9b83')
        title = listing.find("h2")

        houses.append({
            "Price": price.get_text(strip=True) if price else "N/A",
            "Area": area.get_text(strip=True) if area else "N/A",
            "Bedroom": bedroom.get_text(strip=True) if bedroom else "N/A",
            "Title": title.get_text(strip=True) if title else "N/A"

        })

    time.sleep(random.uniform(2, 5))


df = pd.DataFrame(houses)
df

import requests
from bs4 import BeautifulSoup
import pandas as pd
# giving url
url = 'https://www.zameen.com/Residential_Plots/Lahore_Johar_Town-93-1.html'
headers = {
    "User-Agent":"Mozilla/5.0"
}
response = requests.get(url,headers=headers)
soup = BeautifulSoup(response.text, "html.parser")
plots = soup.find_all('li',class_='a37d52f0')
len(plots)

prices = soup.find_all('div',class_='_2923a568')
for price in prices:
    print(price.get_text())
len(prices)

titles = soup.find_all('h2')
for title in titles:
    print(title.get_text())

areas = soup.find_all('div',class_='f0835674')
for area in areas:
  print(area.get_text())
len(areas)

locations = soup.find_all('div',class_='db1aca2f')
for location in locations:
  print(location.get_text())
len(locations)

added= soup.find_all("div",class_="_11acd4eb")
for add in added:
  print(add.get_text())

prices = []
areas = []
locations = []
added = []
titles = []
for plot in plots:
  price = plot.find('div',class_='_2923a568').text.strip()
  prices.append(price)
  area = plot.find('div',class_='f0835674').text.strip()
  areas.append(area)
  location = plot.find('div',class_='db1aca2f').text.strip()
  locations.append(location)
  add = plot.find("div",class_="_11acd4eb").text.strip()
  added.append(added)
  title = plot.find("h2").text.strip()
  titles.append(title)

data = {
    'prices' :prices,
    'areas' :areas,
    'locations' :location,
    'titles' : titles
}
df = pd.DataFrame(data)
df

import requests
from bs4 import BeautifulSoup
import pandas as pd
import random
import time

# User-Agents list
user_agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/112.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/103.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Version/15.1 Safari/605.1.15"
]

plots = []

# Loop through pages 1 to 25
for page in range(1, 26):
    print(f"Scraping page {page}...")
    url = f"https://www.zameen.com/Residential_Plots_Property/Lahore_Johar_Town-93-{page}.html"
    headers = {
        "User-Agent": random.choice(user_agents)
    }

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    listings = soup.find_all('li',class_='a37d52f0')

    for listing in listings:
        price = listing.find('div',class_='_2923a568')
        area = listing.find('div',class_='f0835674')
        location = listing.find('div',class_='db1aca2f')
        title = listing.find('h2')
        add = listing.find('div',class_='_11acd4eb')

        plots.append({
            'price':price.get_text(strip=True) if price else "N/A",
            'area':area.get_text(strip=True) if area else "N/A",
            'location':location.get_text(strip=True) if location else "N/A",
            'title':title.get_text(strip=True) if title else "N/A",
            'add':add.get_text(strip=True) if add else "N/A"

        })

    time.sleep(random.uniform(2, 5))


df = pd.DataFrame(plots)
df